### ISSUE TITLE
new tag/release?

### ISSUE THREAD

**Issue by hydrapolic** [jhunt/hatop#3]
Hello, I'd like to create an updated Gentoo Linux package, would be great to use an official version number instead of an arbitrary git commit. Any plans on tagging a python3 version?

Thanks!

**Comment by jhunt** [comment]
Sure!  I'll get an official rev cut tonight or tomorrow morning.

**Comment by jhunt** [comment]
Take https://github.com/jhunt/hatop/releases/tag/v0.8.0 for a spin.  I uploaded the `hatop` script as an asset on the GitHub release, so you should be able to just download it and go, without cloning the repo or anything.

**Comment by hydrapolic** [comment]
Fantastic, thank you!
